### PR TITLE
Fix mangasee

### LINKED ISSUE #66: Please add mangaseeonline.us
Could you please add: http://mangaseeonline.us/ - it used to be mangasee.com but have been fully redesigned. It also has a bar at the top that used to cover the images when zoomed in fullscreen. Could you look into that, too?

### PR DESCRIPTION
**Pull request by Vorror**
Fixes #66

### CODE REVIEW

**Comment by bb010g** [comment]
Could these commits be squashed?

**Comment by Vorror** [comment]
@bb010g I squashed them, but I don't think it was necessary since github allows a user to automatically squash a pull request.

**Comment by anka-213** [comment]
@Vorror Is this ready to be merged?

**Comment by Vorror** [comment]
@anka-213 yes

**Comment by kobuki** [comment]
Good work! All Pages seems to work as well.

I see an issue though. The first image of any single chapter is shown in the original layout, not stretched to the window. A page-next click snaps it to place and subsequent pages are displayed according to the WCR settings.

**Pull request merged**
