### PR TITLE
Remove debugger in run_script()

### PR DESCRIPTION
**Pull request by stephenbe**
Hello,

Thank you for continuing this great script. I noticed that there was a `debugger` in one of the global functions. I think it would be smart to remove it because I personally don't think this should be in a prodution file.

First PR, hopefully the first of many! 

Thanks!

### CODE REVIEW

**Comment by anka-213** [comment]
I'm a bit conflicted on this one. On one hand, I agree, on the other hand, I find it very convenient. Since there is no way to put breakpoints in a userscript from Crome Developer tools, without stopping there first, I'd have to add it every time I want to debug the script.

"... hopefully first of many!" Yay! I'd love having a co-developer on this. :D

**Comment by stephenbe** [comment]
Hmm I understand the problem, maybe we could do a production version and distribution version. 

What do you think? People would just install the distribution without the debugger.

**Comment by stephenbe** [comment]
If not we can close this.

**Comment by anka-213** [comment]
After thinking a bit more, I'll merge this. Thanks.

**Pull request merged**
