### PR TITLE
Fixes for various sites, added in several additional ones (Updated: 2019-08-06)

### PR DESCRIPTION
**Pull request by SoraHjort**
- Megatokyo
    ] switched over to https://, set include to be http*:// to solve and future proof

- GrrlPower
    ] switched over to https://, set include to be http*:// to solve and future proof

- The Wotch: 
    ] Fixed loading, as well implemented a max width since several images recently have been 2500+ wide
    ] Removed include for http://thewotch.com as that redirects to http://www.thewotch.com

- The Wotch: Cheer
    ] Fixed new URL
    ] other fixes to get script to run, since it switched to wordpress from whatever it was before

- SGVY: updated Includes to the new url at montrose.is/sgvy/archives

- Misfile: Fixed img url matching

- NerfNow!:  
    ] Fixed includes. 
    ] Remove redundant extra include as it redirects to the www prefix
    ] Removed the comment pages include (unable to get them to load)

- e-hentai:
    ] combined the two e-hentai includes to be a single under http*:// instead of https:// and http://
    ] removed the /s, as it was not needed, and limited where you could turn on the script if you're someone who doesn't keep it on 24/7

- exhentai: same changes as e-hentai.

Had to stop at this point, as I kept finding more and more. And I had yet had my dinner.

### CODE REVIEW

**Comment by SoraHjort** [comment]
Added support for Atomic Robo - http://www.atomic-robo.com

**Comment by SoraHjort** [comment]
Minor fix for comics on KatBox.

At some point I'll look into seeing how to fix Bob and George's issues with using images in the author commentary instead of the comic, unable to load the additional images for the annuals, and what else I'm not remembering at the moment.

**Comment by SoraHjort** [comment]
Several fixes for EGSComics, Atomic Robo, and Gunnerkrigg. (Page loading, stretched comic page, and script just not loading, in that order)

Started work on adding DHSComix comics.

Note: I've been using the script on my phone these past few months. Been great for touch screen use, especially with some sites where the nav buttons are a bit asinine. It's also one of the big reasons why I've been adding in some comics, as well as finding broken ones.

**Comment by SoraHjort** [comment]
Alright, not going to be touching this pull anymore, consider it static and ready for merging if approved.
Removed DHS Comix till I can figure out the multiple images per page issue I've ran into it and other sites (if possible... It may be above my tier to figure out)

Changes for last commit:

Fixed: https://github.com/anka-213/webcomic_reader/issues/133

Added: Comics on Furaffinity using the built in comic navigation.

Any additional stuff will be in a new pull.

**Comment by SoraHjort** [comment]
Ok, with a bunch of commits done within the last 24 hours, as well as getting a comic (and it sub comics) I'm currently reading through all setup... It's probably going to be a while before I make any more changes. Unless something comes up. 

Getting DHS Comix setup was a learning experience, what with it having some pages with multiple images. I'm not happy with the workaround's setup, but all things considering, it works.

**Comment by anka-213** [comment]
Is this ready for merging?

**Comment by SoraHjort** [comment]
Yes

**Pull request merged**
